### ISSUE TITLE
What happened to the glossary?

### ISSUE THREAD

**Issue by AnonymousJS-blip** [trashgomi/mojique-translation#103]
Did it move or was it deleted?

**Comment by trashgomi** [comment]
Yep, glossary has been moved to [Zoho](https://sheet.zoho.com/sheet/published.do?rid=hbvaibb530e19e4cb4abb98d4309d30b9433c). Version control for the glossaries just made things more difficult.

See commit d57b0a5e485b99739ef9e847b82f1a4ca25089d8.
