### ISSUE TITLE
Commonevents line 37

### ISSUE THREAD

**Issue by trashgomi** [trashgomi/mojique-translation#14]
This appears to be a reference to common event 115.
Leave this line alone until we figure out how it works.

**Comment by AnonymousJS-blip** [comment]
From what I can find, this line of text occurs within common event 115 itself. Upon further investigation, common event 115 is set to require explicit calling to run but is never called by any other event. I think we can safely ignore this line.

I think that maybe event 115 was a scrapped version of some kind of status display as it sets various variables that crudely translate to the location of various elements of Hamuko's (only her) status window before calling an event (common event 116) that seems to handle actually displaying those elements. Event 115 likely ran continuously in a previous version as its trigger switch is set to the tutorial's completion.

**Comment by trashgomi** [comment]
Nice. Closing this until further notice.
