### ISSUE TITLE
Why are we using a binary format for translation data?

### ISSUE THREAD

**Issue by AnonymousJS-blip** [trashgomi/mojique-translation#94]
Why are we using a binary format for our translation data?

Currently, whenever a change is made, there is no easy way of telling the difference between two files without opening both in an editor and going through each line by line. Git allows for tracking of changes but only for files stored in a text based format. 

How about we use something like CSV (comma separated values) or, more practically for this application, TSV (tab separated values) so that we can see better at a glance what was changed. As a bonus, Github can actually render a preview for these types of files too :).

**Comment by AnonymousJS-blip** [comment]
Oh dear lord, Excel does not like the CSV by default. Why, O Microsoft, do you refuse to make using Unicode easy?
\>:-(

Edit: found the fix, the file must be saved as UTF-8 with BOM so Excel knows it's Unicode. I will make a pull request that fixes the problematic file(s).

**Comment by trashgomi** [comment]
> 
> 
> Why are we using a binary format for our translation data?
> 
> Currently, whenever a change is made, there is no easy way of telling the difference between two files without opening both in an editor and going through each line by line. Git allows for tracking of changes but only for files stored in a text based format.
> 
> How about we use something like CSV (comma separated values) or, more practically for this application, TSV (tab separated values) so that we can see better at a glance what was changed. As a bonus, Github can actually render a preview for these types of files too :).

Hi @AnonymousJS-blip - this has been a matter of much debate and thought.
There are a lot of advantages to using other formats, but these files are also output by Translator++ which has a limited number of options.
Also, it should be easy to copy-paste multi-line translations from these files, which is much easier from spreadsheet files than .csv files.
I have also considered porting everything into a CAT tool for the long-haul, but the programs I've seen don't appear to have as many advantages as disadvantages - namely, lack of columns.

Please contact me on Discord (trashゴミ#7244) or by email (trashgomi@protonmail.com) so I can get you a copy of Translator++, if you're interested. Alternatively, you can open .ods files with Excel or LibreOffice.
